# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|
    config.vm.network :forwarded_port, guest: 3306, host: 3306, auto_correct: true
    config.vm.network :forwarded_port, guest: 5000, host: 5000, auto_correct: true
    config.vm.network :forwarded_port, guest: 9500, host: 9500, auto_correct: true

    (1 .. 9).each do |i|
      outsidePath = ENV["SYNC_OUTSIDE_#{i}"]
      insidePath = ENV["SYNC_INSIDE_#{i}"]
      if outsidePath!=nil && outsidePath!="" && insidePath!=nil && insidePath!="" 
        #print "#{i} = #{rootPath}\n"
        config.vm.synced_folder outsidePath, insidePath
      end
    end

    #within that virtualbox server, use the Official Ubuntu Server 14.04 LTS
    config.vm.box = "ubuntu/trusty64"

    #this says we are doing this stuff in virtualbox    
    config.vm.provider "virtualbox" do |vm|
      vm.memory = 1024
    end

    #this installs docker onto the box
    config.vm.provision "docker" do |docker|

    end
end

